site_name: DupeGrouper # Documentation
theme:
  name: material

nav:
  - Home: index.md
  # - Installation: installation.md
  # - Usage: usage.md
  - API Reference: api/index.html

repo_url: https://github.com/VictorAut/dupe-grouper/
