[tool.poetry]
name = "dupe-grouper"
version = "0.1.0"
description = ""
authors = ["VictorAutonell-Oiry <victora@profusion.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
